name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - r-base=4.0
  - plotly
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - r-scikitlearn
  - dypylr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - stringr
